### ISSUE TITLE
前後串接有問題的部分(雲端)

### ISSUE THREAD

**Issue by HUANG-SIH-MAN** [yuanliif/ac-twitter#16]
1.註冊帳號的頁面，無法按取消跳回登入頁面
2.在側邊的TOP10點擊追蹤後，正在追隨者的數量並不會有變化，後端資料庫是有正確建立關係
![image](https://user-images.githubusercontent.com/87868469/155929851-178ce25d-ad4c-481f-b590-cb07ed199573.png)

**Comment by erase2004** [comment]
- 問題一已修正，在本地

**Comment by HUANG-SIH-MAN** [comment]
OK，剩下發現的問題我重寫新的issue

**Comment by erase2004** [comment]
[完成推文與回覆頁](https://github.com/yuanliif/AC-twitter/pull/18)
PR已整併進main，問題一應該獲得修正

**Comment by HUANG-SIH-MAN** [comment]
註冊帳號的頁面，無法按取消跳回登入頁面，確定已解決
