### ISSUE TITLE
追隨者與正在追蹤前端這裡是否有寫相反

### ISSUE THREAD

**Issue by HUANG-SIH-MAN** [yuanliif/ac-twitter#17]
應該是正在追蹤的其他使用者有3位，目前沒有其他追隨者吧?
前端版面顯示部分
![image](https://user-images.githubusercontent.com/87868469/155934978-20f91421-2731-459d-b04c-0701aef5a1d6.png)
後端API路由回復
![image](https://user-images.githubusercontent.com/87868469/155935246-f667c637-3abb-4efb-b49c-d26f4c72b3d3.png)
資料庫狀態
![image](https://user-images.githubusercontent.com/87868469/155935361-51e36b50-8023-41f1-94d0-cceda6073f51.png)

**Comment by erase2004** [comment]
1. 這邊已確認問題，並在本地端修正

註：issue請在問題確認在正式環境被修正後才關閉issue

**Comment by erase2004** [comment]
[完成推文與回覆頁](https://github.com/yuanliif/AC-twitter/pull/18)
PR已整併進main，問題一應該獲得修正

**Comment by HUANG-SIH-MAN** [comment]
確定已修正
