### ISSUE TITLE
後台登入頁面提示錯誤

### ISSUE THREAD

**Issue by HUANG-SIH-MAN** [yuanliif/ac-twitter#20]
在後台登入時帳號輸入root，密碼故意輸入錯誤，會跳出帳號錯誤的提示訊息
![image](https://user-images.githubusercontent.com/87868469/155954576-2bad0e73-1dc6-4433-958a-ab97fa76d848.png)

在Heroku去看錯誤訊息，目前後端這裡是回應密碼錯誤，前端版面需要再更正
![image](https://user-images.githubusercontent.com/87868469/155954662-8b5764d2-0b53-4b08-861a-e2666f9a0bfd.png)

**Comment by erase2004** [comment]
已經merge進main，可以再確認了

**Comment by HUANG-SIH-MAN** [comment]
確認已做出修正!!
