### ISSUE TITLE
使用者的name、account過長，後台顯示所有使用者清單會破版

### ISSUE THREAD

**Issue by HUANG-SIH-MAN** [yuanliif/ac-twitter#21]
![image](https://user-images.githubusercontent.com/87868469/155956052-fcb5a794-1051-409e-84c5-6c9a190d230f.png)

如果把帳號和姓名的長度都寫到極限長度20和50字的版面
![image](https://user-images.githubusercontent.com/87868469/155956583-8e3b963e-a436-4141-a54e-e83bb3302a0e.png)

![image](https://user-images.githubusercontent.com/87868469/155957066-41b0b78b-e0b2-4fd6-afe8-56f7528b526b.png)

**Comment by martinchiu** [comment]
已解決後台面對過長的暱稱跟帳號會破版的問題

**Comment by HUANG-SIH-MAN** [comment]
確認已解決問題
