### ISSUE TITLE
錯誤提示顯示問題

### ISSUE THREAD

**Issue by HUANG-SIH-MAN** [yuanliif/ac-twitter#22]
使用者修改帳戶設定頁面，如果帳戶資料有填寫錯誤會有錯誤提示，但改成正確格式送出後，錯誤提示依舊不會消失
以使用者體驗來講會不太好，感覺很奇怪，前端如果完成所有版面有空的話，可以修一下

![image](https://user-images.githubusercontent.com/87868469/155961373-18eeed2e-effb-4e7a-88f2-161892bb070a.png)

**Comment by erase2004** [comment]
已經merge進main，可以再確認了

**Comment by HUANG-SIH-MAN** [comment]
確認已經修改，沒有問題
