### ISSUE TITLE
token是undefined時可以進入首頁，但資料無法載入

### ISSUE THREAD

**Issue by HUANG-SIH-MAN** [yuanliif/ac-twitter#23]
要取得token是undefined的狀態，先去後台登入頁面輸入錯誤的帳密按下登入，就可以取得
![image](https://user-images.githubusercontent.com/87868469/155977431-e0019b5d-5cff-46cd-9c80-24b77684b3d5.png)

再按前台登入就可以進入首頁，而非前台登入頁
![image](https://user-images.githubusercontent.com/87868469/155976582-0e48eb2b-0b75-4fc4-addd-ad472303f8a0.png)

會無法載入資料是因為前端攜帶的token是錯誤的，所以後端的API並不會回應資料
![image](https://user-images.githubusercontent.com/87868469/155998927-424be6bf-9034-4a58-b225-58d856509c31.png)

**Comment by erase2004** [comment]
已經merge進main，可以再確認了

**Comment by HUANG-SIH-MAN** [comment]
確認後台登入頁面能正常運作
輸入錯誤的帳密都有正確的提示
不能取得undefined token
