### ISSUE TITLE
在瀏覽其他使用者的頁面，是否追隨使用者的按鈕需要即時更新，不然會錯誤

### ISSUE THREAD

**Issue by HUANG-SIH-MAN** [yuanliif/ac-twitter#25]
如果正在觀看的使用者有再Popular清單裡，按Popular內的跟隨，再按小鈴鐺旁邊的跟隨，會出現錯誤
希望前端這裡只要有按其中一個跟隨按鈕，或是取消跟隨，兩邊的按鈕都要同步更新到
![image](https://user-images.githubusercontent.com/87868469/155978065-bbbe178b-869a-4a82-99fc-8743ee0a729a.png)

因為該使用者已經有跟隨，若再發送一次請求，後端這裡會發送錯誤告訴使用者已經正在追蹤

![image](https://user-images.githubusercontent.com/87868469/155978120-c44a6419-26d2-44bc-af22-d591465ec53e.png)
![image](https://user-images.githubusercontent.com/87868469/155999434-5a09a4e9-2655-4580-bb67-82eccca0c2bc.png)

**Comment by erase2004** [comment]
另外一個情況會是左邊操作時，右邊沒有更新，這要再想想看怎麼兩邊妥善解決

**Comment by HUANG-SIH-MAN** [comment]
確認已修正
