### ISSUE TITLE
個人頁面中的喜歡的內容，點擊like和回復的圖示都會有問題

### ISSUE THREAD

**Issue by HUANG-SIH-MAN** [yuanliif/ac-twitter#27]
無法透過點擊愛心，加入或移除最愛
![image](https://user-images.githubusercontent.com/87868469/155995493-691e4785-6d1d-44de-ae6f-a97952fa865d.png)

主要是因為你們API輸入的網址有錯
![image](https://user-images.githubusercontent.com/87868469/155997980-f1a6ca9c-b40f-4141-affe-2bb2a2ca6d48.png)

點擊對話窗會變成這樣
![image](https://user-images.githubusercontent.com/87868469/155995998-cb0efaa7-0b25-4a67-992f-48b84c2e3191.png)

主要是因為你們API輸入的網址有錯
![image](https://user-images.githubusercontent.com/87868469/155997216-a0a008b2-c258-4d3e-aa7a-879429af731b.png)

不確定是不是因為前端版面還沒有完成的緣故

**Comment by erase2004** [comment]
要再確認看看前端元件的資料流處理

**Comment by erase2004** [comment]
對了，回覆的Modal還沒好，所以點擊回覆是沒有反應的

**Comment by erase2004** [comment]
已經merge進main，待確認

註：回覆的Modal還沒好，所以點擊回覆是沒有反應的

**Comment by HUANG-SIH-MAN** [comment]
點擊愛心可以正常新增或取消追蹤

**Comment by martinchiu** [comment]
點擊愛心可以正常新增或取消追蹤

**Comment by HUANG-SIH-MAN** [comment]
回復按鈕可以正常運作，沒問題
