### ISSUE TITLE
在首頁新建立的貼文，點擊愛心與回覆按鈕會有問題

### ISSUE THREAD

**Issue by HUANG-SIH-MAN** [yuanliif/ac-twitter#29]
發生這樣的狀況，只需進入首頁後，在首頁上方新增的推文，新增推文後如果網頁沒有重新整理在載入一次，點擊下方的愛心和回復都會出錯

主要是因為前端傳送的tweetId是錯誤的，這樣後端API會回復 "Error: 輸入錯誤的tweetId，沒有此推文"
![image](https://user-images.githubusercontent.com/87868469/156091815-63a63958-df28-471d-be73-1c132248db45.png)

推文頁面部分
![image](https://user-images.githubusercontent.com/87868469/156092050-ebf6e76b-74e3-4f92-ac64-34498209db67.png)

**Comment by erase2004** [comment]
這我要看後端有沒有回覆創建的id資訊，沒有的話，就可能採取重刷整個列表的策略了

**Comment by HUANG-SIH-MAN** [comment]
後端這裡有成功建立
![image](https://user-images.githubusercontent.com/87868469/156093935-fbe9fabd-b6e6-47d5-bb27-4bca40f0b6d1.png)

資料庫部分
![image](https://user-images.githubusercontent.com/87868469/156094066-3e101f71-50f2-49a1-a6a5-b466154f7885.png)

**Comment by erase2004** [comment]
**後端有沒有回覆創建的id資訊**

這裡是要看後端回傳的資料裡面，有沒有id資訊，沒有的話，目前那只能採取刷新列表的處理方式

**Comment by HUANG-SIH-MAN** [comment]
回復資料是沒有給，你們前端需要的話，我加上去，除了ID資料你們還需要什麼嗎?

**Comment by erase2004** [comment]
就`id`和`createdAt`

**Comment by HUANG-SIH-MAN** [comment]
請問你們前端再新增留言，也會遇到相同問題嗎?
還是新增推文和留言成功，我都再回復新增的資料
以新增推文為例，回傳格式為
```
{
    "status": "success",
    "message": "新增推文成功",
    "tweetData": {
        "id": 1,
        "description": "tghgfhgfhtrutyiuty",
        "userId": 1,
        "updatedAt": "2022-03-01T02:56:19.993Z",
        "createdAt": "2022-03-01T02:56:19.993Z"
    }
}
```

**Comment by erase2004** [comment]
留言沒有額外的操作，可以不用回覆`replyData`

**Comment by HUANG-SIH-MAN** [comment]
後端這裡已經在master和heroku做更新了

**Comment by erase2004** [comment]
對了，回覆的Modal還沒好，所以點擊回覆是沒有反應的

**Comment by erase2004** [comment]
修正已經merge進main，可以先驗收like和unlike的部份

**Comment by HUANG-SIH-MAN** [comment]
可以在首頁新建立的貼文，點擊愛心，加入或移除最愛都會成功

**Comment by martinchiu** [comment]
在首頁新建立的貼文，也可以正常按愛心加入最愛，再按一次愛心也可以移除最愛

**Comment by HUANG-SIH-MAN** [comment]
回復按鈕也可以成功運作
