### ISSUE TITLE
登出前如果有查看top10 的api 結果，有時候在登出時會跳出錯誤

### ISSUE THREAD

**Issue by martinchiu** [yuanliif/ac-twitter#30]
如果在使用網頁時，查看top10 的api 結果 登出時會跳出錯誤訊息
![image](https://user-images.githubusercontent.com/87409284/156093494-ed5dd3e6-6cfd-4dd8-8853-2a40816025a3.png)
但沒特別用devtool 查看api 回傳的結果的話，目前測起來正常

**Comment by HUANG-SIH-MAN** [comment]
補充API回傳結果，主因是因為登出後token已被清除，所以後端API不會回應資料
但不確定為什麼前端再登出後還會要求TOP10的資料

![image](https://user-images.githubusercontent.com/87868469/156099689-c6aa56ad-cc12-4446-8889-462b2b53b3ef.png)

**Comment by erase2004** [comment]
已經merge進main，待確認

**Comment by martinchiu** [comment]
有嘗試過幾次登出前去查看top 10 api 結果，都沒有在登出時跳出錯誤

**Comment by HUANG-SIH-MAN** [comment]
確認沒有在登出時跳出錯誤，已經修正完畢
