### ISSUE TITLE
首頁推文排序錯誤

### ISSUE THREAD

**Issue by martinchiu** [yuanliif/ac-twitter#31]
![image](https://user-images.githubusercontent.com/87409284/156094893-83adcb7c-6dee-4a1c-8581-d356d829f78a.png)
有幾次登入後在首頁看到的推文排序沒有完全按照時間來排，看api 回傳的結果的確有按照時間來給資料

**Comment by martinchiu** [comment]
重新整理一樣出錯
![image](https://user-images.githubusercontent.com/87409284/156095630-eafdba7d-fbc4-4d44-b390-2c8a36cdf36c.png)

**Comment by erase2004** [comment]
這裡沒有觀測到，如果再遇到的話，請附上devtools的主控台輸出，看有沒有錯誤，謝謝

或者請 @HUANG-SIH-MAN 再確認一次看看

**Comment by HUANG-SIH-MAN** [comment]
我自己也有遇到，但沒有截圖到，還在找會出現的機制到底是什麼

**Comment by martinchiu** [comment]
排序錯誤，主控台這邊沒報錯
![image](https://user-images.githubusercontent.com/87409284/156100991-0c7da6a3-a2dd-4fb1-a207-d0baf479859a.png)
console 最下面的訊息應該是叫我安裝vue 的套件，跟我們討論的內容應該沒關

**Comment by HUANG-SIH-MAN** [comment]
我在chrome和edge都有遇到相同狀況，後來嘗試是如果在不同時間點，但使用相同的帳號(不登出再登入)，發有相同內容的推文，在首頁的排序就會錯亂，但開發者工具的確不會顯示錯誤訊息

chrome版
![image](https://user-images.githubusercontent.com/87868469/156118751-16dfbc08-46d6-4e51-b2f3-848c19096744.png)

但開發者工具的確不會顯示錯誤訊息
edge版
![image](https://user-images.githubusercontent.com/87868469/156118829-3952ad6e-a5c8-49e0-a1e0-81819b4cd17a.png)

有時候又無法觸發錯誤

**Comment by HUANG-SIH-MAN** [comment]
另一種出現的情形，一樣是同一使用者在不同時間點發兩次推文，但首頁正常顯示，登出後我註冊新帳號再登入進去看首頁內容，推文順序又有出錯

後端API回傳的推文排序依舊沒錯
![image](https://user-images.githubusercontent.com/87868469/156121221-8d7a0b92-d27a-45e3-bcb8-b2bf9ff26f2a.png)

開發者工具回報
![image](https://user-images.githubusercontent.com/87868469/156121447-19d862b1-ec09-4307-a3e3-a6fb4c17c6af.png)
![image](https://user-images.githubusercontent.com/87868469/156121575-acba4996-370d-4818-9012-31fdf8591391.png)

**Comment by martinchiu** [comment]
我這邊觀察到的跟鰻魚燒說的一樣，如果是同一使用者發相同內容的文，會出現排序錯誤，而且是兩個相同的文一起出錯

**Comment by HUANG-SIH-MAN** [comment]
附註：
1.有時候不會出現，但將網頁再重新整理後又會出現(多重新整理幾次)
2.個人資訊頁，下方的推文排序也會有同樣的狀況
![image](https://user-images.githubusercontent.com/87868469/156130158-313d4ae5-0929-411a-a4cd-8db0e00d82b9.png)

**Comment by erase2004** [comment]
已經merge進main，待確認

**Comment by martinchiu** [comment]
我這邊用不同帳號重複發相同的文，並重新整理後，頁面排序還是正確的，在個人的推文頁面也是正確的

**Comment by HUANG-SIH-MAN** [comment]
沒有排序錯誤的問題了，但是在檢測時發現另一個問題
在首頁發推文，一開始的顯示時間是錯誤的，為什麼麼發文時間是幾秒後?

![image](https://user-images.githubusercontent.com/87868469/156284007-5dd7edd0-27bd-4b00-a8a2-b6fe4371203a.png)

**Comment by erase2004** [comment]
這可能是瀏覽器和後端伺服器的時間有差距導致的吧，那邊顯示是用瀏覽器回覆的時間，不然就是要塞使用者端瀏覽器的時間

**Comment by martinchiu** [comment]
我這邊發了幾次推文，沒遇到推文時間顯示「幾秒後」

**Comment by erase2004** [comment]
時間修正已經merge進main，最推推文的顯示時間會採用瀏覽器這邊的時間

**Comment by HUANG-SIH-MAN** [comment]
確認更新沒有問題
