### ISSUE TITLE
新增推文字數限制未跳出字數上限提示

### ISSUE THREAD

**Issue by martinchiu** [yuanliif/ac-twitter#32]
在 Acceptance Criteria  跟 AC 給的 UI 都要求新增貼文時，若字數超過１４０字要給錯誤提示，但現在的機制是字數超過的話，就不能再輸入字，好像跟規格要求的有落差

**Comment by erase2004** [comment]
我們是強制輸入框就有限制了，你也可以在前端操作讓他操作140字，然後產生那個錯誤訊息

**Comment by HUANG-SIH-MAN** [comment]
我自己從其他網站複製超過140以上的文字，貼上進入首頁發貼文的輸入窗，只能貼進入剛好140字，剩下多餘的部分無法複製進去輸入框，輸入框也不會顯示字數不可超過140字的提示

複製這些文字，只能貼上紅色區塊內的文字
![image](https://user-images.githubusercontent.com/87868469/156112079-31a58276-6f58-48f9-9ca8-86311ac226f8.png)

發推文頁面，因為無法輸入到140字以上，因此無法看到錯誤訊息
![image](https://user-images.githubusercontent.com/87868469/156112190-117de424-53f9-4be7-ad51-19481fef1c6a.png)


設計稿部分
![image](https://user-images.githubusercontent.com/87868469/156111754-bd60ead2-7f6a-4236-a523-a259350b73dd.png)

會覺得與設計搞和Acceptance Criteria的設定是不相符的
![image](https://user-images.githubusercontent.com/87868469/156112436-9b1af300-0ef6-4f2c-864a-1b535934343d.png)

**Comment by HUANG-SIH-MAN** [comment]
還是這個問題詢問AC是否可以直接在輸入框做限制

**Comment by erase2004** [comment]
和 #26 相似，應一併處理
