### ISSUE TITLE
編輯個人資料，自我介紹輸入到上限160字，版面會破版

### ISSUE THREAD

**Issue by HUANG-SIH-MAN** [yuanliif/ac-twitter#33]
如題，自我介紹輸入到上限160字，再將輸入框滾動條拉到最下面，自我介紹和輸入的第一行字會重疊

![image](https://user-images.githubusercontent.com/87868469/156110040-5c12656e-4766-46f3-9078-ebbd6e6de231.png)

**Comment by erase2004** [comment]
![Snipaste_2022-03-01_19-43-44](https://user-images.githubusercontent.com/1367757/156163283-4dd62ec3-a057-4675-88ed-58cca8aedc5f.png)

輸入框會調整成這樣子的形式，避免輸入框內的文字和label文字重疊，不過右邊出現的scroll就不會是整個`輸入框區域`的高度了

**Comment by erase2004** [comment]
已經merge進main，可以進行驗收了

**Comment by martinchiu** [comment]
我這邊驗收沒問題，不會有破版

**Comment by HUANG-SIH-MAN** [comment]
測試後不會破版，驗收OK，但有發現新問題
前端版面顯示字數未達上限，但後端API回復判斷字數已達上限
初步推測是有空白跳行，前後端判斷標準不同
後端這裡先確認原因
![image](https://user-images.githubusercontent.com/87868469/156288750-eb8b3f9f-cc48-47da-8c88-85587e05c9d6.png)

**Comment by HUANG-SIH-MAN** [comment]
確認這裡前端跳行會算一個字
但在後端因為換行會是 /n ，算兩個字，因此後端的API會跳錯誤訊息，輸入的自我介紹超過上限

**Comment by martinchiu** [comment]
用 safari 瀏覽器編輯使用者資料，他會避免這個錯誤，他會對於換行字元定義為２個字
用 chrome 就會出現鰻魚燒說的錯誤

**Comment by HUANG-SIH-MAN** [comment]
後端這裡有再修正，PR審核中

**Comment by HUANG-SIH-MAN** [comment]
後端修正完畢，再請前端檢查一下
@erase2004
