### ISSUE TITLE
在個人的顯示推文頁面也會出現排序錯誤

### ISSUE THREAD

**Issue by martinchiu** [yuanliif/ac-twitter#34]
![image](https://user-images.githubusercontent.com/87409284/156129064-a35ecedb-f164-43f4-9621-2946f4ffb375.png)
如題，在個人所發的總推文頁面也會出現排序錯誤，目前觀察到的是內容相同的文會排錯

**Comment by erase2004** [comment]
已經merge進main，待確認

**Comment by martinchiu** [comment]
我這邊用不同帳號重複發相同的文，並重新整理後，頁面排序還是正確的，在個人的推文頁面也是正確的

**Comment by martinchiu** [comment]
我這邊用不同帳號重複發相同的文，並重新整理後，頁面排序還是正確的，在個人的推文頁面也是正確的

**Comment by HUANG-SIH-MAN** [comment]
驗收通過，排序都是正確的
