### ISSUE TITLE
增加回推資料在推文刪除後，在沒有原始推文資訊下的顯示處理

### ISSUE THREAD

**Issue by erase2004** [yuanliif/ac-twitter#36]
起源：
https://github.com/martinchiu/twitter-api-2020/issues/27

由於後端的回覆資料，在原始推文被刪除的情況下，
會沒有回覆對象的資訊，因此前端在顯示上會需要做特別的處理，
目前的想法是改顯示`原推文對象已不存在`

**Comment by erase2004** [comment]
已經merge進main，可以進行驗收了

**Comment by martinchiu** [comment]
我在使用者喜歡的推文下看到這個
![image](https://user-images.githubusercontent.com/87409284/156282908-755d834d-e19a-4e3b-8f77-a23441705ade.png)
這也是當喜歡推文被刪除後前端所做的處理嗎？

**Comment by martinchiu** [comment]
看到前端針對回推的推文被刪掉後，回推上原先要顯示發推文人的ＩＤ的處理
![image](https://user-images.githubusercontent.com/87409284/156283314-0a0fae7a-c1d5-489c-93cd-d215ec7d833c.png)

**Comment by HUANG-SIH-MAN** [comment]
建議如果刪除推文的話，連同回復、最愛資料一起刪除，不要顯示在頁面上
前端在修理這個Bug會比較快速方便，我們後端這裡資料庫關聯刪除設定好即可

照目前顯示的方式，整個版面資料流動會很奇怪，因為顯示出來的版面還是有很多連結可以點，點下前往的頁面都是錯誤有問題的

只需要先發一個貼文再加入最愛，去後台刪除該貼文，再去前台個人頁面中的喜歡內容，點擊已被刪除的推文畫面
![20220302_115908](https://user-images.githubusercontent.com/87868469/156292500-3db3caa0-42eb-4989-9eb7-6a91f00f2737.gif)

**Comment by martinchiu** [comment]
刪除推文時連動把關聯的回覆及使用者喜歡的資料一起刪掉，的確是最方便也不會出錯的
如果想避免上面鰻魚燒提到在點擊被刪除推文資料後，版面會怪怪的，我想到的方法是如果推文是被刪除的狀態就不要在版面呈現上加入連結，單純顯示資料就好

**Comment by HUANG-SIH-MAN** [comment]
後端這裡有修正刪除推文資料會同步刪除最愛，目前從新驗收版面是正常的
