### ISSUE TITLE
在未登入的情況下，輸入網址可以進入登入、註冊以外的頁面

### ISSUE THREAD

**Issue by HUANG-SIH-MAN** [yuanliif/ac-twitter#41]
會不符合user story 和Acceptance Criteria 的標準

網址輸入
http://localhost:8080/#/home
![image](https://user-images.githubusercontent.com/87868469/156352322-fc721583-1aab-4e55-80e0-6927ad765e2d.png)

http://localhost:8080/#/user/184/tweets
![image](https://user-images.githubusercontent.com/87868469/156352442-1a6811e4-8c2c-4771-9dda-4be7812b304c.png)

剩下嘗試的網址，我就不截圖了，後端這裡的API都有檔，但前端都沒有跳轉回登入頁，並給予提示
ttp://localhost:8080/#/setting
http://localhost:8080/#/tweet/514
http://localhost:8080/#/user/4/replies
http://localhost:8080/#/user/2/likes
http://localhost:8080/#/

另外測試後台的網址，是有成功跳轉到後台登入頁面，不確定是否要給提示說必須先登入
http://localhost:8080/#/admin/tweets
http://localhost:8080/#/admin/users

**Comment by HUANG-SIH-MAN** [comment]
初步推測發生的原因
如果先用本地端的後端API，登入取得token，再將API網址改用heroku
再輸入網址跳轉到其他頁面，而不走正規登入流程
前端這裡會判斷使用者會取得token，所以可以進入網頁
但是後端這裡的API會判定token是錯誤的，因為使用該token並不會找到使用者資料，才回應message: "沒有提供正確的authencation token"

**Comment by erase2004** [comment]
修正已經更新上main

**Comment by HUANG-SIH-MAN** [comment]
確認已修正bug，能夠成功跳轉到登入頁面
