### ISSUE TITLE
沒有「追蹤者」情況下，不會顯示對應畫面「尚無追蹤者」

### ISSUE THREAD

**Issue by HUANG-SIH-MAN** [yuanliif/ac-twitter#42]
不符合Acceptance Criteria

（前端）沒有「追蹤者」情況下，對應畫面顯示為「尚無追蹤者」
![image](https://user-images.githubusercontent.com/87868469/156368366-93c2665c-90aa-49d5-8a7e-30878df24465.png)

（前端）沒有「正在追蹤」情況下，對應畫面顯示為「尚無正在追蹤」
![image](https://user-images.githubusercontent.com/87868469/156368561-f74d51d6-7f7b-441f-8f05-6883d9e4fee7.png)

**Comment by martinchiu** [comment]
已確認修正

**Comment by HUANG-SIH-MAN** [comment]
確認修正成功
