### ISSUE TITLE
註冊遇到的錯誤不會在更新後消失

### ISSUE THREAD

**Issue by martinchiu** [yuanliif/ac-twitter#43]
![image](https://user-images.githubusercontent.com/87409284/156373820-3caed586-f9e8-4400-9e77-be954a672ccb.png)
我一開始root 當帳號註冊，跳出帳號註冊過，但我在修改後再送出，信箱被註冊過的錯誤跳出來（的確被註冊過），但是帳號重複的錯誤訊息沒有消失

**Comment by martinchiu** [comment]
已解決註冊時跑出的錯誤訊息，會在更新後消失

**Comment by HUANG-SIH-MAN** [comment]
確定問題已解決
