### ISSUE TITLE
再顯示追隨者，自我介紹太長，會導致版面破版

### ISSUE THREAD

**Issue by HUANG-SIH-MAN** [yuanliif/ac-twitter#44]
只要自我介紹其中一段的太長有機率觸發，英文介紹容易出現，中文介紹不會有問題

![image](https://user-images.githubusercontent.com/87868469/156379908-1ba18e8d-eaac-441f-b794-b179d1bbaf92.png)

**Comment by erase2004** [comment]
修正已經更新上main

**Comment by martinchiu** [comment]
![image](https://user-images.githubusercontent.com/87409284/156465199-3887e57e-524e-4d39-9618-6427b5ef50f4.png)
我這邊還是會出現相同的錯誤

**Comment by HUANG-SIH-MAN** [comment]
ZZZ那個人的頭像被壓縮到有修好
但是自我介紹會破版的問題還是存在

![image](https://user-images.githubusercontent.com/87868469/156481289-c236341a-1d5e-4dae-97b7-a66182da00a7.png)

**Comment by HUANG-SIH-MAN** [comment]
確認修正成功

**Comment by martinchiu** [comment]
確認修正成功
